#include <iostream>
#include "knowledgeBase.h"

// Constructor
KnowledgeBase::KnowledgeBase() {}

enum Diagnosis {
	LUNG_CANCER,
	BREAST_CANCER,
	ESOPHAGEAL_CANCER,
	COLORECTAL_CANCER,
	BLADDER_CANCER,
	LYMPHOMA,
	CERVICAL_CANCER,
	MELANOMA,
	BONE_CANCER,
	PANCREATIC_CANCER,
	BRAIN_CANCER,
	LEUKEMIA,
	THYROID_CANCER,
	PROSTATE_CANCER,
	LIVER_CANCER,
	NASOPHARYNGEAL_CANCER,
	STOMACH_CANCER,
	SPINAL_CANCER,
	OVARIAN_CANCER,
	ORAL_CANCER,
	LARYNGEAL_CANCER,
	SINONASAL_CANCER,
	DIAGNOSIS_COUNT // To keep track of total diagnoses
};

enum Symptom {
    PERSISTENT_COUGH,
    WEIGHT_LOSS,
    CHEST_PAIN,
    LUMP_IN_BREAST,
    NIPPLE_DISCHARGE,
    SKIN_DIMPLING,
    DIFFICULTY_SWALLOWING,
    HOARSENESS,
    ACID_REFLUX,
    BLOOD_IN_STOOL,
    PERSISTENT_ABDOMINAL_PAIN,
    FREQUENT_URINATION,
    BLOOD_IN_URINE,
    PELVIC_PAIN,
    NIGHT_SWEATS,
    PAINLESS_SWOLLEN_LYMPH_NODES,
    PERSISTENT_FATIGUE,
    UNUSUAL_VAGINAL_BLEEDING,
    PAINFUL_INTERCOURSE,
    MOLE_CHANGES,
    IRREGULAR_MOLE_BORDERS,
    MOLE_BLEEDING,
    UNEXPLAINED_BONE_PAIN,
    FREQUENT_FRACTURES,
    SWELLING_NEAR_BONE,
    JAUNDICE,
    UPPER_ABDOMINAL_PAIN,
    TROUBLE_SPEAKING,
    MUSCLE_WEAKNESS,
    PERSISTENT_HEADACHE,
    SYMPTOM_COUNT // This ensures we know the number of symptoms
};

void KnowledgeBase::print() { cout << "Testing KnowledgeBase ..." << endl; }